all:
	$(CC) $(FLAGS) -o ../obj/factor.o factor.cpp
	$(CC) $(FLAGS) -o ../obj/monomial.o monomial.cpp
	$(CC) $(FLAGS) -o ../obj/polyfact.o polyfact.cpp
	$(CC) $(FLAGS) -o ../obj/polynomial.o polynomial.cpp
